name: CI

on: [push]

jobs:
  build-packages:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        platform: [arm_cortex-a7_neon-vfpv4]
        include:
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/bcm27xx/bcm2709/openwrt-sdk-22.03.3-bcm27xx-bcm2709_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a7_neon-vfpv4
            upload_name: ps3netsrv_arm_cortex-a7_neon-vfpv4
            build_path: openwrt-sdk-22.03.3-bcm27xx-bcm2709_gcc-11.2.0_musl_eabi.Linux-x86_64
    steps:
    - uses: actions/checkout@v4
    - name: build packages
      run: |
        cd $HOME
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        curl \
        file \
        gawk \
        gettext \
        git \
        libncurses5-dev \
        libssl-dev \
        python3 \
        rsync \
        subversion \
        sudo \
        swig \
        unzip \
        wget \
        zlib1g-dev
        wget -c ${{ matrix.sdk_url }}
        tar xf $(basename "${{ matrix.sdk_url }}")
        cd $(basename "${{ matrix.sdk_url }}" .tar.xz)
        echo $USIGN_SECRET | base64 -d > key-build
        echo "src-git ps3netsrv_feed https://github.com/Coolumin/ps3netsrv-openwrt.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/ps3netsrv/download
        make package/ps3netsrv/prepare -j1
        make package/ps3netsrv/compile 
      env:
        USIGN_SECRET: ${{ secrets.USIGN_SECRET }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.upload_name }}
        path: /home/runner/${{ matrix.build_path }}/bin/packages/${{ matrix.platform }}/ps3netsrv_feed/
