name: CI

on: [push]

jobs:
  build-packages:
    runs-on: ubuntu-24.04.3
    strategy:
      max-parallel: 3
      matrix:
        # platform: [mips_24kc, mipsel_24kc, aarch64_cortex-a53, aarch64_cortex-a72, arm_cortex-a9_vfpv3-d16, mips_4kec, mips_mips32, mipsel_24kc_24kf, mipsel_74kc, mipsel_mips32, mips64_octeonplus, powerpc_464fp, powerpc_8540, aarch64_generic, arc_archs, arm_arm926ej-s, arm_arm1176jzf-s_vfp, arm_cortex-a15_neon-vfpv4, arm_cortex-a5_vfpv4, arm_cortex-a7, arm_cortex-a7_neon-vfpv4, arm_cortex-a8_vfpv3, arm_cortex-a9, arm_cortex-a9_neon, arm_fa526, arm_mpcore, arm_xscale, x86_64, i386_pentium4, i386_pentium-mmx]
        platform: [mips_24kc, mipsel_24kc, aarch64_cortex-a53, aarch64_cortex-a72, arm_cortex-a9_vfpv3-d16, mips_4kec, mips_mips32, mipsel_24kc_24kf, mipsel_74kc, mipsel_mips32, mips64_octeonplus, powerpc_464fp, powerpc_8540, aarch64_generic, arm_arm926ej-s, arm_arm1176jzf-s_vfp, arm_cortex-a15_neon-vfpv4, arm_cortex-a5_vfpv4, arm_cortex-a7, arm_cortex-a7_neon-vfpv4, arm_cortex-a8_vfpv3, arm_cortex-a9, arm_cortex-a9_neon, arm_fa526, arm_mpcore, arm_xscale, x86_64, i386_pentium4, i386_pentium-mmx]
        include:
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/ath79/generic/openwrt-sdk-22.03.3-ath79-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: mips_24kc
            upload_name: ps3netsrv_mips_24kc
            build_path: openwrt-sdk-22.03.3-ath79-generic_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: mipsel_24kc
            upload_name: ps3netsrv_mipsel_24kc
            build_path: openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/mvebu/cortexa53/openwrt-sdk-22.03.3-mvebu-cortexa53_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: aarch64_cortex-a53
            upload_name: ps3netsrv_aarch64_cortex-a53
            build_path: openwrt-sdk-22.03.3-mvebu-cortexa53_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/mvebu/cortexa72/openwrt-sdk-22.03.3-mvebu-cortexa72_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: aarch64_cortex-a72
            upload_name: ps3netsrv_aarch64_cortex-a72
            build_path: openwrt-sdk-22.03.3-mvebu-cortexa72_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/mvebu/cortexa9/openwrt-sdk-22.03.3-mvebu-cortexa9_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a9_vfpv3-d16
            upload_name: ps3netsrv_arm_cortex-a9_vfpv3-d16
            build_path: openwrt-sdk-22.03.3-mvebu-cortexa9_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/realtek/rtl838x/openwrt-sdk-22.03.3-realtek-rtl838x_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: mips_4kec
            upload_name: ps3netsrv_mips_4kec
            build_path: openwrt-sdk-22.03.3-realtek-rtl838x_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/bcm63xx/generic/openwrt-sdk-22.03.3-bcm63xx-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: mips_mips32
            upload_name: ps3netsrv_mips_mips32
            build_path: openwrt-sdk-22.03.3-bcm63xx-generic_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/pistachio/generic/openwrt-sdk-22.03.3-pistachio_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: mipsel_24kc_24kf
            upload_name: ps3netsrv_mipsel_24kc_24kf
            build_path: openwrt-sdk-22.03.3-pistachio_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/bcm47xx/mips74k/openwrt-sdk-22.03.3-bcm47xx-mips74k_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: mipsel_74kc
            upload_name: ps3netsrv_mipsel_74kc
            build_path: openwrt-sdk-22.03.3-bcm47xx-mips74k_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/bcm47xx/generic/openwrt-sdk-22.03.3-bcm47xx-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: mipsel_mips32
            upload_name: ps3netsrv_mipsel_mips32
            build_path: openwrt-sdk-22.03.3-bcm47xx-generic_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/octeon/generic/openwrt-sdk-22.03.3-octeon-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: mips64_octeonplus
            upload_name: ps3netsrv_mips64_octeonplus
            build_path: openwrt-sdk-22.03.3-octeon-generic_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/apm821xx/nand/openwrt-sdk-22.03.3-apm821xx-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: powerpc_464fp
            upload_name: ps3netsrv_powerpc_464fp
            build_path: openwrt-sdk-22.03.3-apm821xx-nand_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/mpc85xx/p1010/openwrt-sdk-22.03.3-mpc85xx-p1010_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: powerpc_8540
            upload_name: ps3netsrv_powerpc_8540
            build_path: openwrt-sdk-22.03.3-mpc85xx-p1010_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/layerscape/armv8_64b/openwrt-sdk-22.03.3-layerscape-armv8_64b_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: aarch64_generic
            upload_name: ps3netsrv_aarch64_generic
            build_path: openwrt-sdk-22.03.3-layerscape-armv8_64b_gcc-11.2.0_musl.Linux-x86_64
          #- sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/archs38/generic/openwrt-sdk-22.03.3-archs38-generic_gcc-11.2.0_glibc.Linux-x86_64.tar.xz
          #  platform: arc_archs
          #  upload_name: ps3netsrv_arc_archs
          #  build_path: openwrt-sdk-22.03.3-archs38-generic_gcc-11.2.0_glibc.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/at91/sam9x/openwrt-sdk-22.03.3-at91-sam9x_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_arm926ej-s
            upload_name: ps3netsrv_arm_arm926ej-s
            build_path: openwrt-sdk-22.03.3-at91-sam9x_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/bcm27xx/bcm2708/openwrt-sdk-22.03.3-bcm27xx-bcm2708_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_arm1176jzf-s_vfp
            upload_name: ps3netsrv_arm_arm1176jzf-s_vfp
            build_path: openwrt-sdk-22.03.3-bcm27xx-bcm2708_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/armvirt/32/openwrt-sdk-22.03.3-armvirt-32_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a15_neon-vfpv4
            upload_name: ps3netsrv_arm_cortex-a15_neon-vfpv4
            build_path: openwrt-sdk-22.03.3-armvirt-32_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/at91/sama5/openwrt-sdk-22.03.3-at91-sama5_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a5_vfpv4
            upload_name: ps3netsrv_arm_cortex-a5_vfpv4
            build_path: openwrt-sdk-22.03.3-at91-sama5_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/mediatek/mt7629/openwrt-sdk-22.03.3-mediatek-mt7629_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a7
            upload_name: ps3netsrv_arm_cortex-a7
            build_path: openwrt-sdk-22.03.3-mediatek-mt7629_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/bcm27xx/bcm2709/openwrt-sdk-22.03.3-bcm27xx-bcm2709_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a7_neon-vfpv4
            upload_name: ps3netsrv_arm_cortex-a7_neon-vfpv4
            build_path: openwrt-sdk-22.03.3-bcm27xx-bcm2709_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/omap/generic/openwrt-sdk-22.03.3-omap_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a8_vfpv3
            upload_name: ps3netsrv_arm_cortex-a8_vfpv3
            build_path: openwrt-sdk-22.03.3-omap_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/bcm53xx/generic/openwrt-sdk-22.03.3-bcm53xx-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a9
            upload_name: ps3netsrv_arm_cortex-a9
            build_path: openwrt-sdk-22.03.3-bcm53xx-generic_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/imx/cortexa9/openwrt-sdk-22.03.3-imx-cortexa9_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a9_neon
            upload_name: ps3netsrv_arm_cortex-a9_neon
            build_path: openwrt-sdk-22.03.3-imx-cortexa9_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/gemini/generic/openwrt-sdk-22.03.3-gemini_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_fa526
            upload_name: ps3netsrv_arm_fa526
            build_path: openwrt-sdk-22.03.3-gemini_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/oxnas/ox820/openwrt-sdk-22.03.3-oxnas-ox820_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_mpcore
            upload_name: ps3netsrv_arm_mpcore
            build_path: openwrt-sdk-22.03.3-oxnas-ox820_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/kirkwood/generic/openwrt-sdk-22.03.3-kirkwood_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_xscale
            upload_name: ps3netsrv_arm_xscale
            build_path: openwrt-sdk-22.03.3-kirkwood_gcc-11.2.0_musl_eabi.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/x86/64/openwrt-sdk-22.03.3-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: x86_64
            upload_name: ps3netsrv_x86_64
            build_path: openwrt-sdk-22.03.3-x86-64_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/x86/generic/openwrt-sdk-22.03.3-x86-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: i386_pentium4
            upload_name: ps3netsrv_i386_pentium4
            build_path: openwrt-sdk-22.03.3-x86-generic_gcc-11.2.0_musl.Linux-x86_64
          - sdk_url: https://downloads.openwrt.org/releases/22.03.3/targets/x86/geode/openwrt-sdk-22.03.3-x86-geode_gcc-11.2.0_musl.Linux-x86_64.tar.xz
            platform: i386_pentium-mmx
            upload_name: ps3netsrv_i386_pentium-mmx
            build_path: openwrt-sdk-22.03.3-x86-geode_gcc-11.2.0_musl.Linux-x86_64
    steps:
    - uses: actions/checkout@v1
    - name: build packages
      run: |
        cd $HOME
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        curl \
        file \
        gawk \
        gettext \
        git \
        libncurses5-dev \
        libssl-dev \
        python2.7 \
        python3 \
        rsync \
        subversion \
        sudo \
        swig \
        unzip \
        wget \
        zlib1g-dev
        wget -c ${{ matrix.sdk_url }}
        tar xf $(basename "${{ matrix.sdk_url }}")
        cd $(basename "${{ matrix.sdk_url }}" .tar.xz)
        echo $USIGN_SECRET | base64 -d > key-build
        echo "src-git ps3netsrv_feed https://github.com/jhonathanc/ps3netsrv-openwrt.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/ps3netsrv/download
        make package/ps3netsrv/prepare
        make package/ps3netsrv/compile
      env:
        USIGN_SECRET: ${{ secrets.USIGN_SECRET }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.upload_name }}
        path: /home/runner/${{ matrix.build_path }}/bin/packages/${{ matrix.platform }}/ps3netsrv_feed/
