name: CI

on: [push]

jobs:
  build-packages:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [mips_24kc, mipsel_24kc, aarch64_cortex-a53, aarch64_cortex-a72, arm_cortex-a9_vfpv3-d16, mips_4kec, mips_mips32, mipsel_24kc_24kf, mipsel_74kc, mipsel_mips32, mips64_octeonplus, powerpc_464fp, powerpc_8540, aarch64_generic, arc_arc700, arc_archs, arm_arm926ej-s, arm_arm1176jzf-s_vfp, arm_cortex-a15_neon-vfpv4, arm_cortex-a5_vfpv4, arm_cortex-a7, arm_cortex-a7_neon-vfpv4, arm_cortex-a8_vfpv3, arm_cortex-a9, arm_cortex-a9_neon, arm_fa526, arm_mpcore, arm_xscale, x86_64, i386_pentium4, i386_pentium-mmx],
        sdk_url: [
          mips_24kc: https://downloads.openwrt.org/releases/22.03.3/targets/ath79/generic/openwrt-sdk-22.03.3-ath79-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          mipsel_24kc: https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          aarch64_cortex-a53: https://downloads.openwrt.org/releases/22.03.3/targets/mvebu/cortexa53/openwrt-sdk-22.03.3-mvebu-cortexa53_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          aarch64_cortex-a72: https://downloads.openwrt.org/releases/22.03.3/targets/mvebu/cortexa72/openwrt-sdk-22.03.3-mvebu-cortexa72_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          arm_cortex-a9_vfpv3-d16: https://downloads.openwrt.org/releases/22.03.3/targets/mvebu/cortexa9/openwrt-sdk-22.03.3-mvebu-cortexa9_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          mips_4kec: https://downloads.openwrt.org/releases/22.03.3/targets/realtek/rtl838x/openwrt-sdk-22.03.3-realtek-rtl838x_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          mips_mips32: https://downloads.openwrt.org/releases/22.03.3/targets/bcm63xx/generic/openwrt-sdk-22.03.3-bcm63xx-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          mipsel_24kc_24kf: https://downloads.openwrt.org/releases/22.03.3/targets/pistachio/generic/openwrt-sdk-22.03.3-pistachio_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          mipsel_74kc: https://downloads.openwrt.org/releases/22.03.3/targets/bcm47xx/mips74k/openwrt-sdk-22.03.3-bcm47xx-mips74k_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          mipsel_mips32: https://downloads.openwrt.org/releases/22.03.3/targets/bcm47xx/generic/openwrt-sdk-22.03.3-bcm47xx-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          mips64_octeonplus: https://downloads.openwrt.org/releases/22.03.3/targets/octeon/generic/openwrt-sdk-22.03.3-octeon-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          powerpc_464fp: https://downloads.openwrt.org/releases/22.03.3/targets/apm821xx/nand/openwrt-sdk-22.03.3-apm821xx-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          powerpc_8540: https://downloads.openwrt.org/releases/22.03.3/targets/mpc85xx/p1010/openwrt-sdk-22.03.3-mpc85xx-p1010_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          aarch64_generic: https://downloads.openwrt.org/releases/22.03.3/targets/layerscape/armv8_64b/openwrt-sdk-22.03.3-layerscape-armv8_64b_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          arc_archs: https://downloads.openwrt.org/releases/22.03.3/targets/archs38/generic/openwrt-sdk-22.03.3-archs38-generic_gcc-11.2.0_glibc.Linux-x86_64.tar.xz,
          arm_arm926ej-s: https://downloads.openwrt.org/releases/22.03.3/targets/at91/sam9x/openwrt-sdk-22.03.3-at91-sam9x_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_arm1176jzf-s_vfp: https://downloads.openwrt.org/releases/22.03.3/targets/bcm27xx/bcm2708/openwrt-sdk-22.03.3-bcm27xx-bcm2708_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_cortex-a15_neon-vfpv4: https://downloads.openwrt.org/releases/22.03.3/targets/armvirt/32/openwrt-sdk-22.03.3-armvirt-32_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_cortex-a5_vfpv4: https://downloads.openwrt.org/releases/22.03.3/targets/at91/sama5/openwrt-sdk-22.03.3-at91-sama5_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_cortex-a7: https://downloads.openwrt.org/releases/22.03.3/targets/mediatek/mt7629/openwrt-sdk-22.03.3-mediatek-mt7629_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_cortex-a7_neon-vfpv4: https://downloads.openwrt.org/releases/22.03.3/targets/bcm27xx/bcm2709/openwrt-sdk-22.03.3-bcm27xx-bcm2709_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_cortex-a8_vfpv3: https://downloads.openwrt.org/releases/22.03.3/targets/omap/generic/openwrt-sdk-22.03.3-omap_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_cortex-a9: https://downloads.openwrt.org/releases/22.03.3/targets/bcm53xx/generic/openwrt-sdk-22.03.3-bcm53xx-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_cortex-a9_neon: https://downloads.openwrt.org/releases/22.03.3/targets/imx/cortexa9/openwrt-sdk-22.03.3-imx-cortexa9_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_fa526: https://downloads.openwrt.org/releases/22.03.3/targets/gemini/generic/openwrt-sdk-22.03.3-gemini_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_mpcore: https://downloads.openwrt.org/releases/22.03.3/targets/oxnas/ox820/openwrt-sdk-22.03.3-oxnas-ox820_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          arm_xscale: https://downloads.openwrt.org/releases/22.03.3/targets/kirkwood/generic/openwrt-sdk-22.03.3-kirkwood_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz,
          x86_64: https://downloads.openwrt.org/releases/22.03.3/targets/x86/64/openwrt-sdk-22.03.3-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          i386_pentium4: https://downloads.openwrt.org/releases/22.03.3/targets/x86/generic/openwrt-sdk-22.03.3-x86-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz,
          i386_pentium-mmx: https://downloads.openwrt.org/releases/22.03.3/targets/x86/geode/openwrt-sdk-22.03.3-x86-geode_gcc-11.2.0_musl.Linux-x86_64.tar.xz
		    ],
        upload_name: [
          mips_24kc: ps3netsrv_mips_24kc,
          mipsel_24kc: ps3netsrv_mipsel_24kc,
          aarch64_cortex-a53: ps3netsrv_aarch64_cortex-a53,
          aarch64_cortex-a72: ps3netsrv_aarch64_cortex-a72,
          arm_cortex-a9_vfpv3-d16: ps3netsrv_arm_cortex-a9_vfpv3-d16,
          mips_4kec: ps3netsrv_mips_4kec,
          mips_mips32: ps3netsrv_mips_mips32,
          mipsel_24kc_24kf: ps3netsrv_mipsel_24kc_24kf,
          mipsel_74kc: ps3netsrv_mipsel_74kc,
          mipsel_mips32: ps3netsrv_mipsel_mips32,
          mips64_octeonplus: ps3netsrv_mips64_octeonplus,
          powerpc_464fp: ps3netsrv_powerpc_464fp,
          powerpc_8540: ps3netsrv_powerpc_8540,
          aarch64_generic: ps3netsrv_aarch64_generic,
          arc_archs: ps3netsrv_arc_archs,
          arm_arm926ej-s: ps3netsrv_arm_arm926ej-s,
          arm_arm1176jzf-s_vfp: ps3netsrv_arm_arm1176jzf-s_vfp,
          arm_cortex-a15_neon-vfpv4: ps3netsrv_arm_cortex-a15_neon-vfpv4,
          arm_cortex-a5_vfpv4: ps3netsrv_arm_cortex-a5_vfpv4,
          arm_cortex-a7: ps3netsrv_arm_cortex-a7,
          arm_cortex-a7_neon-vfpv4: ps3netsrv_arm_cortex-a7_neon-vfpv4,
          arm_cortex-a8_vfpv3: ps3netsrv_arm_cortex-a8_vfpv3,
          arm_cortex-a9: ps3netsrv_arm_cortex-a9,
          arm_cortex-a9_neon: ps3netsrv_arm_cortex-a9_neon,
          arm_fa526: ps3netsrv_arm_fa526,
          arm_mpcore: ps3netsrv_arm_mpcore,
          arm_xscale: ps3netsrv_arm_xscale,
          x86_64: ps3netsrv_x86_64,
          i386_pentium4: ps3netsrv_i386_pentium4,
          i386_pentium-mmx: ps3netsrv_i386_pentium-mmx
		    ]
    steps:
    - uses: actions/checkout@v1
    - name: build packages
      run: |
        cd $HOME
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        curl \
        file \
        gawk \
        gettext \
        git \
        libncurses5-dev \
        libssl-dev \
        python2.7 \
        python3 \
        rsync \
        subversion \
        sudo \
        swig \
        unzip \
        wget \
        zlib1g-dev
        wget -c ${{ matrix.sdk_url }}
        tar xf $(basename "${{ matrix.sdk_url }}")
        cd $(basename "${{ matrix.sdk_url }}" .tar.xz)
        echo $USIGN_SECRET | base64 -d > key-build
        echo "src-git ps3netsrv_feed https://github.com/jhonathanc/ps3netsrv-openwrt.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/ps3netsrv/download
        make package/ps3netsrv/prepare
        make package/ps3netsrv/compile
      env:
        USIGN_SECRET: ${{ secrets.USIGN_SECRET }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.upload_name }}
        path: /home/runner/$(basename "${{ matrix.sdk_url }}" .tar.xz)/bin/packages/${{ matrix.platform }}/ps3netsrv_feed/
